export const NUMBER_APOD_IMAGES = 3;
export const TIME_CHANGE_SLIDE_APOD = 5000;

export const CUSTOM_CONFIG_LOGIN = {
  LOGIN_BY_EMAIL: true,
  LOGIN_BY_GOOGLE_ACCOUNT: true,
  LOGIN_BY_FACEBOOK_ACCOUNT: false
};