const Types = {
  GET_APOD: "GET_APOD",
  GET_APOD_SUCCESS: "GET_APOD_SUCCESS",
  GET_APOD_FAILED: "GET_APOD_FAILED",

  // Login const
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_GOOGLE_ACCOUNT_REQUEST: "LOGIN_GOOGLE_ACCOUNT_REQUEST",
  LOGIN_FACEBOOK_ACCOUNT_REQUEST: "LOGIN_FACEBOOK_ACCOUNT_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  VERIFY_REQUEST: "VERIFY_REQUEST",
  VERIFY_SUCCESS: "VERIFY_SUCCESS",
  VERIFY_FAILURE: "VERIFY_FAILURE",
  
  // REGISTER
  SIGN_ON_REQUEST: "SIGN_ON_REQUEST",
  SIGN_ON_SUCCESS: "SIGN_ON_SUCCESS",
  SIGN_ON_FAILURE: "SIGN_ON_FAILURE",
  
  // UPDATE PROFILE
  UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",
};

export default Types;